# Generated by Django 5.1.1 on 2024-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdata",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="studentdata",
            name="school",
        ),
        migrations.RemoveField(
            model_name="studentdata",
            name="state",
        ),
        migrations.AddField(
            model_name="studentdata",
            name="additional_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
