# Generated by Django 5.1.1 on 2024-10-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0002_remove_studentdata_class_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdata",
            name="additional_data",
            field=models.JSONField(default=dict),
        ),
    ]
